/**
 * The stylesheet, written from the motion the rig itself computed.
 *
 * `content/brand/orb/motion.json` is the record the renderer made while the real component played
 * each move in a real browser: the translate, the scale and the rotation the rig wrote onto its own
 * SVG, frame by frame, plus the spark exactly as the rig draws it when motion is reduced. This
 * module turns that record into `apps/web-pwa/src/ui/orb-moves.css`, and the test regenerates it and
 * compares, so the sheet can never drift from the character. Nobody edits it by hand.
 *
 * What the sheet is FOR: every surface that shows the orb as a picture rather than as the live rig
 * — the 404, the public site, a popup, a mail preview. In the app proper the rig plays these moves
 * itself; the sheet carries the body half of each one, to the same numbers.
 */

import { WOBO_TONES, type WoboTones } from '../../packages/wobo/src/identity.ts';
import {
  MOVE_NAMES,
  MOVES,
  ORB_SIZE,
  type OrbKeyframe,
  type OrbMoveName,
  type OrbProp,
  propSvg,
  RIG_SIZE,
  stagePercent,
  svgDataUri,
  VIEW_BOX,
} from './moves.ts';

/** One frame of the rig's own body transform, in the rig's units and degrees. */
export interface OrbFrame {
  dx: number;
  dy: number;
  sx: number;
  sy: number;
  rot: number;
}

export interface OrbMotion {
  /** What made this, so a reader of the JSON knows it was not typed. */
  renderedBy: string;
  rig: {
    viewBox: string;
    /** The orb's box and the stage it sits in, in px. */
    size: number;
    stage: number;
    /** What the rig squashes and turns about, in its own units. */
    pivot: { x: number; y: number };
  };
  /** The rig's own spark group, lifted out of the rendered DOM with its own transform. */
  spark: string;
  tracks: Record<string, OrbFrame[]>;
}

const round = (v: number) => {
  const r = Math.round(v * 1000) / 1000;
  return Object.is(r, -0) ? 0 : r;
};

/** Rig units as a percentage of the orb's own box, which is what a CSS translate wants. */
const units = (v: number) => round((v * 100) / VIEW_BOX.size);

function transformOf(frame: OrbFrame): string {
  return `translate(${units(frame.dx)}%, ${units(frame.dy)}%) scale(${round(frame.sx)}, ${round(frame.sy)}) rotate(${round(frame.rot)}deg)`;
}

const KEBAB: Record<string, string> = {
  transform: 'transform',
  opacity: 'opacity',
  clipPath: 'clip-path',
  transformOrigin: 'transform-origin',
};

function declarations(frame: OrbKeyframe, indent: string): string {
  return (Object.keys(KEBAB) as (keyof OrbKeyframe)[])
    .filter((key) => key !== 'offset' && frame[key] !== undefined)
    .map((key) => `${indent}${KEBAB[key as string]}: ${frame[key]};`)
    .join('\n');
}

/** A percentage stop, with the trailing zeros a generated file should not carry. */
const stop = (fraction: number) => `${round(fraction * 100)}%`;

function bodyKeyframes(name: string, track: readonly OrbFrame[]): string {
  const transforms = track.map(transformOf);
  // The loop closes on the frame it opened with: every move starts and ends at rest.
  const stops: string[] = [];
  for (let i = 0; i <= transforms.length; i += 1) {
    const value = transforms[i % transforms.length];
    const previous = i > 0 ? transforms[(i - 1) % transforms.length] : null;
    const next = i < transforms.length ? transforms[(i + 1) % transforms.length] : null;
    // A stop that neither starts nor ends a change says nothing a straight line does not.
    if (previous === value && next === value) continue;
    stops.push(`  ${stop(i / transforms.length)} {\n    transform: ${value};\n  }`);
  }
  return `@keyframes ${name} {\n${stops.join('\n')}\n}`;
}

function propKeyframes(name: string, frames: readonly OrbKeyframe[]): string {
  const stops = frames.map((frame) => `  ${stop(frame.offset)} {\n${declarations(frame, '    ')}\n  }`);
  return `@keyframes ${name} {\n${stops.join('\n')}\n}`;
}

function propBackground(prop: OrbProp, tones: WoboTones): string {
  return `url("${svgDataUri(propSvg(prop, tones))}")`;
}

function sparkSvg(spark: string, tones: WoboTones): string {
  const { x, y, size } = { x: VIEW_BOX.x, y: VIEW_BOX.y, size: VIEW_BOX.size };
  const painted = spark.replace(/var\(--wr-eye\)/g, tones.eye);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x} ${y} ${size} ${size}">${painted}</svg>`;
}

export function orbMovesCss(motion: OrbMotion): string {
  const inner = (RIG_SIZE / ORB_SIZE) * 100;
  const inset = round((100 - inner) / 2);
  const pivot = `${round(((motion.rig.pivot.x - VIEW_BOX.x) / VIEW_BOX.size) * 100)}% ${round(((motion.rig.pivot.y - VIEW_BOX.y) / VIEW_BOX.size) * 100)}%`;
  const out: string[] = [];

  out.push(`/*
 * The eight moves, in CSS and SVG. GENERATED by tools/orb/render.mjs from the rig's own motion
 * (content/brand/orb/motion.json) — do not edit this file by hand; edit the move table in
 * tools/orb/moves.ts and render again. apps/web-pwa/src/ui/orb-moves.test.ts regenerates this file
 * and compares it byte for byte, which is how rule 1 of the library (one source) is kept.
 *
 * The markup a surface writes:
 *
 *   <span class="wobo-orb wobo-orb--thinking" style="--wobo-orb-size: 120px">
 *     <span class="wobo-orb__prop wobo-orb__prop--under wobo-orb__prop--1"></span>
 *     <span class="wobo-orb__body"><!-- the orb: the live rig, an <img>, an inline <svg> --></span>
 *     <span class="wobo-orb__prop wobo-orb__prop--over wobo-orb__prop--1"></span>
 *     <span class="wobo-orb__spark"></span>
 *   </span>
 *
 * The prop layers are only needed by the three moves that have one (thinking, drawing, reading);
 * the spark layer is what reduced motion leaves on screen, so every surface carries it.
 *
 * The same eight moves, rendered from the same component, are GIFs for mail in content/brand/orb.
 */`);

  out.push(`.wobo-orb {
  position: relative;
  display: inline-block;
  width: var(--wobo-orb-size, 120px);
  height: var(--wobo-orb-size, 120px);
  line-height: 0;
}

.wobo-orb__body {
  position: absolute;
  inset: ${inset}%;
  z-index: 1;
  transform-origin: ${pivot};
}

.wobo-orb__body > * {
  width: 100%;
  height: 100%;
  display: block;
}

.wobo-orb__prop,
.wobo-orb__spark {
  position: absolute;
  inset: 0;
  background-repeat: no-repeat;
  background-position: center;
  background-size: 100% 100%;
  pointer-events: none;
}

.wobo-orb__prop--under {
  z-index: 0;
}

.wobo-orb__prop--over,
.wobo-orb__spark {
  z-index: 2;
}

/* The spark is not decoration: it is what a still keeps when motion is reduced. */
.wobo-orb__spark {
  opacity: 0;
  background-image: url("${svgDataUri(sparkSvg(motion.spark, WOBO_TONES.light))}");
}`);

  const dark: string[] = [
    `.wobo-orb__spark {
    background-image: url("${svgDataUri(sparkSvg(motion.spark, WOBO_TONES.dark))}");
  }`,
  ];

  for (const name of MOVE_NAMES) {
    const spec = MOVES[name] as (typeof MOVES)[OrbMoveName];
    const track = motion.tracks[name];
    if (!track || track.length === 0) throw new Error(`no rendered motion for ${name}`);
    const duration = spec.frames * spec.frameMs;
    out.push(`/* ${name} — ${spec.says}: ${spec.usedBy.join(', ')} */
${bodyKeyframes(`wobo-orb-${name}`, track)}

.wobo-orb--${name} .wobo-orb__body {
  animation: wobo-orb-${name} ${duration}ms linear infinite;
}`);
    const props = 'props' in spec ? ((spec.props ?? []) as readonly OrbProp[]) : [];
    props.forEach((prop, index) => {
      const layer = `wobo-orb-${name}-prop-${index + 1}`;
      const selector = `.wobo-orb--${name} .wobo-orb__prop--${index + 1}`;
      const rules = [
        `  background-image: ${propBackground(prop, WOBO_TONES.light)};`,
        prop.origin ? `  transform-origin: ${stagePercent(prop.origin)};` : null,
        prop.keyframes.length > 0 ? `  animation: ${layer} ${duration}ms linear infinite;` : null,
      ].filter((line): line is string => line !== null);
      const block = [
        prop.keyframes.length > 0 ? `${propKeyframes(layer, prop.keyframes)}\n` : '',
        `${selector} {\n${rules.join('\n')}\n}`,
      ].join('');
      out.push(block);
      dark.push(
        `${selector} {
    background-image: ${propBackground(prop, WOBO_TONES.dark)};
  }`,
      );
    });
  }

  // Night. The same two selectors the rig's own token layer uses, in the same order, so a surface
  // that has written `data-theme` and one that has not both get the right tones.
  out.push(`[data-theme="dark"] {
  ${dark.join('\n\n  ')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
  ${dark.join('\n\n  ')}
  }
}`);

  // Rule 4 of the library, WITHOUT EXCEPTION: a still, with the spark.
  //
  // TWO SWITCHES, ONE RULE. The device's setting is the media query. The app's own "Reduce motion ·
  // Still frames instead of animation" row on the You screen (`ui/motion.ts`) never touches the
  // device's setting: it stamps `data-motion="reduce"` on the document root instead, and
  // `packages/motion`'s `useReducedMotion` counts that attribute as exactly equal to the media
  // query, in its own words "so a learner without a system-wide preference still gets still frames
  // everywhere the library draws". The app's other sheets answer it the same way
  // (`screens/progress/progress.css`, `screens/learn/Climb.css`, `ui/primitives/ui.css`).
  //
  // A sheet that answered only the media query would leave the orb moving for the learner who asked
  // it to stop, in the one place they were ever offered the ask. So the still is written ONCE here
  // and emitted under both, which is the only way the two can never drift apart.
  const still = (prefix: string, indent: string) =>
    `${indent}${prefix}.wobo-orb__body,
${indent}${prefix}.wobo-orb__prop {
${indent}  animation: none;
${indent}  transform: none;
${indent}}

${indent}${prefix}.wobo-orb__spark {
${indent}  opacity: 1;
${indent}}`;

  out.push(`@media (prefers-reduced-motion: reduce) {
${still('', '  ')}
}`);

  out.push(still('[data-motion="reduce"] ', ''));

  return `${out.join('\n\n')}\n`;
}
