'use client';

/**
 * The board bench — a dev-only harness that plays a golden plan so the hand can be looked at,
 * screenshotted and regression-tested without the brain, the network or a lesson.
 *
 * Two things live here:
 *
 *  1. **The Pythagoras plan**, written in TypeScript, computed in code and marked verified — the
 *     original hand-built golden, kept because it is the readable example of what a plan IS.
 *  2. **The golden gallery**: the twelve boards in `goldens/`, generated by `goldens/build.ts` and
 *     shared byte-for-byte with the brain's own golden test. The gallery is what the Playwright
 *     suite drives, and what a latency measurement is taken from.
 *
 * Reachable only in dev, three ways:
 *   · `/board-bench.html#<name>` — the hermetic page the e2e suite uses (no app, no router, no bus);
 *   · mount `<BoardBenchGate />` anywhere near the root — it shows itself at `#board-bench`;
 *   · or call `window.__woboBoardBench()` from the console.
 *
 * Everything a test needs is on `window.__woboBench` (see `BenchApi`): the names, a play call, the
 * time to the first stroke, and a ledger of what actually landed on the board.
 */

import {
  type BoardEvent,
  BoardStore,
  boardBook,
  parseBoardPlan,
  plane,
  WoboFullBoard,
  WoboPlane,
} from '@wobo/wobo';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { GOLDEN_BOARDS, type GoldenBoard, goldenBoard } from './goldens';
import { GOLDEN_BRAINS } from './goldens/brains';
import { changeVariable } from './variables';

// --- The hand-written golden -------------------------------------------------------------------------

/** The triangle, in board units. A 3-4-5 at forty units to the side. */
const UNIT = 40;
const A = 4 * UNIT; // the horizontal leg
const B = 3 * UNIT; // the vertical leg
const ORIGIN: [number, number] = [250, 400];

/** Computed here, in code, and only then drawn — never a number the model wrote. */
function pythagoras(a: number, b: number) {
  const aSq = a * a;
  const bSq = b * b;
  const cSq = aSq + bSq;
  const c = Math.sqrt(cSq);
  return { a, b, c, aSq, bSq, cSq, verified: Math.abs(aSq + bSq - cSq) < 1e-9 };
}

const T = pythagoras(4, 3);
const C = T.c * UNIT;

/**
 * The outward unit normal of the hypotenuse, so the big square is built away from the triangle
 * rather than on top of it.
 */
const hypNormal: [number, number] = [B / C, -A / C];

const ink = (object: unknown, t: number): BoardEvent => ({ type: 'ink', object, t }) as BoardEvent;

/**
 * The plan, in the order Wobo would draw it, timed against Wobo's voice. Exported so the golden-board
 * test can assert its structure and so QA can replay exactly what shipped.
 */
export const PYTHAGORAS_PLAN: BoardEvent[] = [
  { type: 'say', text: 'Here it is. A right triangle, and a square on every side.', t: 0 },
  ink(
    {
      id: 'x-axis',
      kind: 'axis',
      anchor: { board: [140, 560] },
      orientation: 'x',
      min: 0,
      max: 10,
      step: 1,
      length: 700,
      label: 'x',
      style: { ink: 'faint', weight: 1 },
      t: { start: 0, dur: 700 },
    },
    0,
  ),
  ink(
    {
      id: 'y-axis',
      kind: 'axis',
      anchor: { board: [140, 560] },
      orientation: 'y',
      min: 0,
      max: 7,
      step: 1,
      length: 480,
      label: 'y',
      style: { ink: 'faint', weight: 1 },
      t: { start: 250, dur: 700 },
    },
    250,
  ),
  ink(
    {
      id: 'triangle',
      kind: 'polygon',
      anchor: { board: ORIGIN },
      points: [
        [0, 0],
        [A, 0],
        [0, -B],
      ],
      style: { ink: 'wobo', weight: 2 },
      t: { start: 900, dur: 1100 },
    },
    900,
  ),
  { type: 'say', text: 'Call the legs a and b, and the long side c.', t: 2000 },
  ink(
    {
      id: 'label-a',
      kind: 'label',
      anchor: { board: [ORIGIN[0] + A / 2 - 6, ORIGIN[1] + 14] },
      text: 'a',
      t: { start: 2100, dur: 400 },
    },
    2100,
  ),
  ink(
    {
      id: 'label-b',
      kind: 'label',
      anchor: { board: [ORIGIN[0] - 30, ORIGIN[1] - B / 2 - 12] },
      text: 'b',
      t: { start: 2350, dur: 400 },
    },
    2350,
  ),
  ink(
    {
      id: 'label-c',
      kind: 'label',
      anchor: { board: [ORIGIN[0] + A / 2 + 14, ORIGIN[1] - B / 2 - 30] },
      text: 'c',
      t: { start: 2600, dur: 400 },
    },
    2600,
  ),
  { type: 'say', text: 'Now a square on each one.', t: 3000 },
  ink(
    {
      id: 'square-a',
      kind: 'polygon',
      anchor: { board: ORIGIN },
      points: [
        [0, 0],
        [A, 0],
        [A, A],
        [0, A],
      ],
      style: { ink: 'faint', weight: 1 },
      t: { start: 3100, dur: 1200 },
    },
    3100,
  ),
  ink(
    {
      id: 'square-b',
      kind: 'polygon',
      anchor: { board: ORIGIN },
      points: [
        [0, 0],
        [0, -B],
        [-B, -B],
        [-B, 0],
      ],
      style: { ink: 'faint', weight: 1 },
      t: { start: 4300, dur: 1000 },
    },
    4300,
  ),
  ink(
    {
      id: 'square-c',
      kind: 'polygon',
      anchor: { board: ORIGIN },
      points: [
        [A, 0],
        [0, -B],
        [0 + hypNormal[0] * C, -B + hypNormal[1] * C],
        [A + hypNormal[0] * C, 0 + hypNormal[1] * C],
      ],
      style: { ink: 'accent', weight: 2 },
      t: { start: 5300, dur: 1400 },
    },
    5300,
  ),
  { type: 'say', text: 'The two small squares fill the big one exactly.', t: 6700 },
  ink(
    {
      id: 'law',
      kind: 'tex',
      anchor: { board: [640, 120] },
      tex: 'a^2 + b^2 = c^2',
      size: 40,
      t: { start: 6800, dur: 1600 },
    },
    6800,
  ),
  ink(
    {
      id: 'a-squared',
      kind: 'number',
      anchor: { board: [640, 200] },
      value: T.aSq,
      label: 'a² =',
      verified: T.verified,
      t: { start: 8400, dur: 600 },
    },
    8400,
  ),
  ink(
    {
      id: 'b-squared',
      kind: 'number',
      anchor: { board: [640, 250] },
      value: T.bSq,
      label: 'b² =',
      verified: T.verified,
      t: { start: 9000, dur: 600 },
    },
    9000,
  ),
  ink(
    {
      id: 'c-squared',
      kind: 'number',
      anchor: { board: [640, 300] },
      value: T.cSq,
      label: 'c² =',
      verified: T.verified,
      t: { start: 9600, dur: 700 },
    },
    9600,
  ),
  ink(
    {
      id: 'sum-underline',
      kind: 'underline',
      anchor: { object: 'c-squared' },
      style: { ink: 'accent', weight: 2 },
      t: { start: 10300, dur: 500 },
    },
    10300,
  ),
  { type: 'say', text: 'Sixteen and nine make twenty-five, so c is five.', t: 10500 },
  ink(
    {
      id: 'answer',
      kind: 'write',
      anchor: { board: [640, 370] },
      text: `so c = ${T.c}`,
      size: 34,
      style: { ink: 'accent' },
      t: { start: 10800, dur: 1400 },
    },
    10800,
  ),
  ink(
    {
      id: 'answer-circle',
      kind: 'circle',
      anchor: { object: 'answer' },
      pad: 12,
      style: { ink: 'accent', weight: 2 },
      t: { start: 12200, dur: 900 },
    },
    12200,
  ),
  { type: 'done', t: 13200 },
];

/** The plan as the schema sees it — a bad frame would be dropped here, not drawn. */
export const GOLDEN_PYTHAGORAS = parseBoardPlan(PYTHAGORAS_PLAN);

/** The hand-written plan, wrapped so it sits in the gallery beside the generated twelve. */
const HAND_WRITTEN: GoldenBoard = {
  name: 'pythagoras-handwritten',
  prompt: 'why does a squared plus b squared equal c squared',
  title: 'pythagoras (hand-written plan)',
  presentation: 'full',
  subject: 'math',
  expect: { ids: [], kinds: [], anchors: [], hangsOff: [], written: [], numbers: [] },
  plan: GOLDEN_PYTHAGORAS,
};

/** Everything the bench can play, the generated goldens first. */
export const BENCH_BOARDS: GoldenBoard[] = [...GOLDEN_BOARDS, HAND_WRITTEN];

// --- Playing a plan ------------------------------------------------------------------------------------

export interface PlayOptions {
  /**
   * Land every object at once, at full progress. The board looks exactly as it does when the
   * performance finishes; it just does not take fourteen seconds to get there. Screenshots and
   * structural assertions use it; the latency measurement never does.
   */
  instant?: boolean;
}

/** The plan with all timing collapsed — same objects, same order, no waiting. */
function collapse(plan: BoardEvent[]): BoardEvent[] {
  return plan.map((event) => {
    if (event.type !== 'ink') return { ...event, t: 0 };
    const object = event.object as Record<string, unknown>;
    return { ...event, t: 0, object: { ...object, t: { start: 0, dur: 1 } } } as BoardEvent;
  });
}

/** When the last stroke of a plan has settled, in ms from the start of the utterance. */
function planEndsAt(plan: BoardEvent[]): number {
  let end = 0;
  for (const event of plan) {
    const at = event.t ?? 0;
    const dur =
      event.type === 'ink'
        ? (((event.object as Record<string, unknown>).t as { dur?: number } | undefined)?.dur ??
          1200)
        : 0;
    end = Math.max(end, at + dur);
  }
  return end;
}

/** Play a plan into a store on its own timeline. Returns a cancel. */
function playPlan(store: BoardStore, plan: BoardEvent[], options: PlayOptions = {}): () => void {
  const events = options.instant ? collapse(plan) : plan;
  store.reset();
  store.beginUtterance();
  if (options.instant) {
    for (const event of events) store.applyEvent(event);
    return () => {};
  }
  const timers: ReturnType<typeof setTimeout>[] = [];
  for (const event of events) {
    timers.push(
      setTimeout(() => {
        store.applyEvent(event);
      }, event.t ?? 0),
    );
  }
  return () => {
    for (const t of timers) clearTimeout(t);
  };
}

// --- What a test can see ---------------------------------------------------------------------------------

export interface BenchLedgerRow {
  id: string;
  kind: string;
  /** Which of the four anchor forms placed it (BOARD.md §3) — never "pixels". */
  anchor: string;
  /** The object it hangs off, when it hangs off one. */
  owner?: string;
  verified?: boolean;
}

export interface BenchApi {
  names: string[];
  /** Play a board. Resolves nothing; poll `ready`. */
  play(name: string, options?: PlayOptions): void;
  /** True once the whole plan has landed and settled. */
  ready: boolean;
  /** ms from the start of the utterance to the first stroke in the DOM (BOARD.md §10: under 1 s). */
  firstStrokeMs: number | null;
  /**
   * Where that first stroke was, in viewport px. A stroke nobody could see is not a first stroke
   * (docs/INK-FREEZE-PLAN-TRACE.md §5: the bench requires the stroke inside the viewport).
   */
  firstStrokeBox: { x: number; y: number; w: number; h: number } | null;
  /**
   * ms from the page opening to that same first stroke. The cold number: module evaluation, React
   * mounting, the surface measuring itself, the first geometry pass and the first paint, all in.
   * Set once per page load and never overwritten, so a replay cannot flatter it.
   */
  firstMarkFromLoadMs: number | null;
  /** What the store holds, in ink order. */
  ledger(): BenchLedgerRow[];
  /** Numbers the verifier never passed. The hand refuses them; this is where QA reads them. */
  refused(): string[];
  /** The board on screen. */
  current: string | null;
  /**
   * Fill the board to BOARD.md §10's budget — 2,000 strokes — and hold it there, so the frame rate
   * can be measured against the number the law actually names. `screenAnchor` adds one mark hung
   * off a registered target, which is Wobo's commonest turn and the case that used to collapse: the
   * rAF loop it starts re-anchored and re-elemented all 2,000 objects every frame.
   */
  stress(count: number, options?: { screenAnchor?: boolean }): void;
}

declare global {
  interface Window {
    __woboBench?: BenchApi;
    __woboBenchReady?: boolean;
    __woboBoardBench?: () => void;
  }
}

/**
 * The first mark the hand puts in the DOM, timed from the start of the utterance.
 *
 * "Stroke" here means what BOARD.md §10 means: the pen is moving. A written word counts — a `write`
 * is drawn glyph by glyph under a moving nib and paints no `.wobo-stroke` path at all, so a probe
 * that watched only for stroked paths would report a board that opens on handwriting as slow when
 * the pen had in fact been moving from the first frame.
 */
const FIRST_MARK = '[data-wobo-object] path, [data-wobo-object] text, [data-wobo-object] image';

type Box = { x: number; y: number; w: number; h: number };

/**
 * Where the ink is, in viewport px: the union of every painted mark's rect. A path inside a
 * `<mask>` (the nib revealing a glyph) has no box of its own, and a stroke on its first frame can
 * be a zero-length dash, so this is null until something has a box.
 */
function boxOfInk(root: Element): Box | null {
  let box: Box | null = null;
  for (const el of Array.from(root.querySelectorAll(FIRST_MARK))) {
    if (el.closest('mask')) continue;
    const r = el.getBoundingClientRect();
    if (r.width <= 0 && r.height <= 0) continue;
    if (!box) box = { x: r.x, y: r.y, w: r.width, h: r.height };
    else {
      const x = Math.min(box.x, r.x);
      const y = Math.min(box.y, r.y);
      box = {
        x,
        y,
        w: Math.max(box.x + box.w, r.x + r.width) - x,
        h: Math.max(box.y + box.h, r.y + r.height) - y,
      };
    }
  }
  return box;
}

/**
 * The first mark's time is taken at first sighting; its box is taken as soon as any ink has one,
 * within the next half second, so a glyph's first empty frame does not read as ink off the glass.
 */
function watchFirstStroke(
  root: Element,
  from: number,
  onFirst: (ms: number) => void,
  onBox: (box: Box) => void,
): () => void {
  let boxed = false;
  let deadline: ReturnType<typeof setTimeout> | null = null;
  const tryBox = () => {
    if (boxed) return true;
    const box = boxOfInk(root);
    if (!box) return false;
    boxed = true;
    onBox(box);
    return true;
  };
  let seen = Boolean(root.querySelector(FIRST_MARK));
  if (seen) onFirst(performance.now() - from);
  if (seen && tryBox()) return () => {};
  const observer = new MutationObserver(() => {
    if (!seen) {
      if (!root.querySelector(FIRST_MARK)) return;
      seen = true;
      onFirst(performance.now() - from);
      deadline = setTimeout(() => observer.disconnect(), 500);
    }
    if (tryBox()) {
      observer.disconnect();
      if (deadline) clearTimeout(deadline);
    }
  });
  observer.observe(root, { childList: true, subtree: true, attributes: true });
  return () => {
    observer.disconnect();
    if (deadline) clearTimeout(deadline);
  };
}

// --- The bench --------------------------------------------------------------------------------------------

/**
 * The one registry target the hermetic bench offers: the bench's own chrome, which is a real element
 * with a real rect that moves when the page moves. It is what a `{target}` anchor hangs off here.
 */
const STRESS_TARGET = 'bench-chrome';

const benchTargets = (): readonly { id: string; getRect: () => DOMRect | null }[] => [
  {
    id: STRESS_TARGET,
    getRect: () =>
      document.querySelector('[data-testid="bench-chrome"]')?.getBoundingClientRect() ?? null,
  },
];

/** The name in the hash, if there is one: `#board-bench/tangent-parabola` or `#tangent-parabola`. */
function nameFromHash(hash: string): string | null {
  const raw = hash.replace(/^#/, '').replace(/^board-bench\/?/, '');
  const [name] = raw.split('/');
  return name ? name : null;
}

export function BoardBench(props: { board?: string }) {
  const store = useMemo(() => new BoardStore({ presentation: 'full' }), []);
  const hostRef = useRef<HTMLDivElement>(null);
  const cancelRef = useRef<() => void>(() => {});
  const readyTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const [current, setCurrent] = useState<string>(
    () =>
      props.board ??
      nameFromHash(typeof window === 'undefined' ? '' : window.location.hash) ??
      BENCH_BOARDS[0]?.name ??
      '',
  );
  const [instant, setInstant] = useState(false);
  /** The full board's own chrome — the scrubber and share. Asked for in the hash: `.../chrome`. */
  const [chrome, setChrome] = useState(
    () => typeof window !== 'undefined' && window.location.hash.includes('/chrome'),
  );
  const [, setTick] = useState(0);

  const board = useMemo(
    () => BENCH_BOARDS.find((b) => b.name === current) ?? BENCH_BOARDS[0],
    [current],
  );

  const start = useCallback(
    (name: string, options: PlayOptions = {}) => {
      const next = BENCH_BOARDS.find((b) => b.name === name);
      if (!next) return;
      cancelRef.current();
      clearTimeout(readyTimer.current);
      const api = window.__woboBench;
      if (api) {
        api.ready = false;
        api.firstStrokeMs = null;
        api.firstStrokeBox = null;
        api.current = name;
      }
      window.__woboBenchReady = false;
      setCurrent(name);
      setInstant(options.instant === true);

      // Wipe first, and let the wipe paint, so the clock below starts on a genuinely empty board.
      // Without this a replay would "measure" the previous run's ink still sitting in the DOM.
      store.reset();
      let stopped = false;
      let stopInner = () => {};
      const begin = () => {
        if (stopped) return;
        const from = performance.now();
        const stopWatching = hostRef.current
          ? watchFirstStroke(
              hostRef.current,
              from,
              (ms) => {
                const api = window.__woboBench;
                if (!api) return;
                api.firstStrokeMs = ms;
                if (api.firstMarkFromLoadMs === null) api.firstMarkFromLoadMs = performance.now();
              },
              (box) => {
                const api = window.__woboBench;
                if (api) api.firstStrokeBox = box;
              },
            )
          : () => {};
        const cancelPlan = playPlan(store, next.plan, options);
        // Settled means every object has finished drawing, plus a breath for the last paint.
        const settleIn = options.instant ? 120 : planEndsAt(next.plan) + 400;
        readyTimer.current = setTimeout(() => {
          if (window.__woboBench) window.__woboBench.ready = true;
          window.__woboBenchReady = true;
          setTick((n) => n + 1);
        }, settleIn);
        stopInner = () => {
          cancelPlan();
          stopWatching();
        };
      };
      const outer = requestAnimationFrame(() => {
        const inner = requestAnimationFrame(begin);
        stopInner = () => cancelAnimationFrame(inner);
      });
      cancelRef.current = () => {
        stopped = true;
        cancelAnimationFrame(outer);
        stopInner();
      };
    },
    [store],
  );

  // The API a test drives the bench through. Installed before the first play so nothing races it.
  useEffect(() => {
    const api: BenchApi = {
      names: BENCH_BOARDS.map((b) => b.name),
      play: (name, options) => start(name, options),
      ready: false,
      firstStrokeMs: null,
      firstStrokeBox: null,
      firstMarkFromLoadMs: null,
      current: null,
      ledger: () =>
        store.snapshot().map((state) => {
          const anchor = store.anchorOf(state) as Record<string, unknown> | undefined;
          const form = anchor
            ? (['board', 'object', 'target', 'focus'].find((k) => k in anchor) ?? 'unknown')
            : 'unknown';
          const object = state.object as Record<string, unknown>;
          return {
            id: String(object.id),
            kind: String(object.kind),
            anchor: form,
            ...(form === 'object' ? { owner: String(anchor?.object) } : {}),
            ...('verified' in object ? { verified: object.verified === true } : {}),
          };
        }),
      refused: () => store.refused.map((o) => o.id),
      stress: (count, options) => {
        cancelRef.current();
        clearTimeout(readyTimer.current);
        store.reset();
        // Ink laid down instantly and spread over the whole board, so the virtualiser, the camera
        // and the geometry cache all see a realistic spread rather than 2,000 objects in a heap.
        for (let i = 0; i < count; i++) {
          const x = 20 + ((i * 37) % 960);
          const y = 20 + ((i * 61) % 580);
          store.ink({
            id: `stress-${i}`,
            kind: 'polyline',
            anchor: { board: [x, y] },
            style: { ink: i % 5 === 0 ? 'accent' : 'wobo', weight: 1 },
            t: { start: 0, dur: 1 },
            points: [
              [0, 0],
              [12, -8],
              [22, 4],
            ],
          } as never);
        }
        if (options?.screenAnchor) {
          store.ink({
            id: 'stress-mark',
            kind: 'circle',
            anchor: { target: STRESS_TARGET },
            pad: 10,
            style: { ink: 'accent', weight: 2 },
            t: { start: 0, dur: 1 },
          } as never);
        }
        if (window.__woboBench) window.__woboBench.ready = true;
        window.__woboBenchReady = true;
        setTick((n) => n + 1);
      },
    };
    window.__woboBench = api;
    return () => {
      if (window.__woboBench === api) window.__woboBench = undefined;
    };
  }, [start, store]);

  // Play whatever the hash asks for, and follow it when it changes. `start` is stable (it closes
  // over the store and nothing else), so this mounts the listener once and re-runs only if the
  // store is ever swapped underneath it.
  const fallback = useRef(current);
  fallback.current = current;
  useEffect(() => {
    const fromHash = () => {
      const name = nameFromHash(window.location.hash) ?? fallback.current;
      setChrome(window.location.hash.includes('/chrome'));
      start(name, { instant: window.location.hash.includes('/instant') });
    };
    fromHash();
    window.addEventListener('hashchange', fromHash);
    const timer = readyTimer;
    const cancel = cancelRef;
    return () => {
      window.removeEventListener('hashchange', fromHash);
      cancel.current();
      clearTimeout(timer.current);
      window.__woboBenchReady = false;
    };
  }, [start]);

  /**
   * A bound control moved (docs/BOARD.md §8). The bench has no gateway, so the golden's own
   * generator answers as the brain: the dependants are recomputed and come back as ink frames,
   * through exactly the seam the app drives the gateway through.
   */
  const onVariableChange = useCallback(
    (variable: string, value: number | boolean | string | [number, number]) => {
      const brain = board ? GOLDEN_BRAINS[board.name] : undefined;
      if (!brain) return;
      void changeVariable(store, { variable, value }, brain);
    },
    [board, store],
  );

  /** The same plan on the other surface: the frosted plane, summoned from Wobo's orb. */
  const onPlane = useCallback(() => {
    if (!board) return;
    const id = plane.fresh({ x: window.innerWidth - 72, y: window.innerHeight - 96 });
    playPlan(boardBook.get(id), board.plan);
  }, [board]);

  if (!board) return null;

  return (
    <div
      ref={hostRef}
      data-testid="board-bench"
      data-board={board.name}
      style={{
        background: 'var(--wobo-page, #FFFFFF)',
        inset: 0,
        position: 'fixed',
        zIndex: 2000,
      }}
    >
      <WoboFullBoard
        store={store}
        title={board.title}
        // The scrubber and the share affordance are the full board's own chrome. Off by default so
        // a screenshot is the ink and nothing else; `#board-bench/<name>/chrome` turns them on,
        // which is how the timeline is driven from a test.
        chrome={chrome}
        capture={false}
        targets={benchTargets}
        onVariableChange={onVariableChange}
      />
      {/* The other surface. It draws nothing until it is summoned, so it costs a screenshot
          nothing — and it means the same plan can be watched on the plane from here. */}
      <WoboPlane />
      <div
        data-testid="bench-chrome"
        style={{
          alignItems: 'center',
          display: 'flex',
          flexWrap: 'wrap',
          gap: 8,
          left: 16,
          position: 'absolute',
          right: 16,
          top: 16,
        }}
      >
        <label style={{ alignItems: 'center', display: 'flex', fontSize: 13, gap: 6 }}>
          <span style={{ color: 'var(--wobo-ink-300, #72727C)', lineHeight: '44px' }}>board</span>
          <select
            data-testid="bench-picker"
            aria-label="which golden board to play"
            style={benchControl}
            value={board.name}
            onChange={(e) => {
              window.location.hash = `board-bench/${e.target.value}`;
            }}
          >
            {BENCH_BOARDS.map((b) => (
              <option key={b.name} value={b.name}>
                {b.name}
              </option>
            ))}
          </select>
        </label>
        <button
          type="button"
          onClick={() => start(board.name)}
          data-testid="bench-replay"
          style={benchControl}
        >
          replay
        </button>
        <button
          type="button"
          onClick={() => start(board.name, { instant: true })}
          data-testid="bench-instant"
          style={benchControl}
        >
          land it all
        </button>
        <button type="button" onClick={onPlane} data-testid="bench-plane" style={benchControl}>
          on the plane
        </button>
        <span
          data-testid="bench-status"
          style={{ color: 'var(--wobo-ink-300, #72727C)', fontSize: 13, lineHeight: '44px' }}
        >
          {board.plan.length} events, {store.refused.length} refused
          {instant ? ', landed' : ''}
        </span>
      </div>
      <p
        data-testid="bench-prompt"
        style={{
          // Above the board's own chrome when there is any: the prompt is a caption, and it used to
          // sit exactly over the scrubber and swallow every click meant for it.
          bottom: chrome ? 56 : 14,
          color: 'var(--wobo-ink-300, #72727C)',
          fontSize: 13,
          left: 16,
          margin: 0,
          // It is text about the board, never something to press.
          pointerEvents: 'none',
          position: 'absolute',
          right: 16,
        }}
      >
        {board.prompt}
      </p>
    </div>
  );
}

/**
 * The bench's own controls. It is a dev page, but the responsive matrix walks it now — the board's
 * chrome is mounted nowhere else — so the harness would report the bench's picker and buttons as
 * findings about the product. They sit on the same 44px floor and 13px copy floor every control in
 * the app does, which is also what makes the bench usable on the phone QA actually holds.
 */
const benchControl: React.CSSProperties = {
  fontSize: 13,
  minHeight: 44,
  padding: '0 10px',
};

/**
 * Mount the bench only in dev, only at `#board-bench`. Drop this beside the app's root and QA can
 * reach the hand without a lesson, a network, or the brain.
 */
export function BoardBenchGate() {
  const [on, setOn] = useState(
    () => typeof window !== 'undefined' && window.location.hash.startsWith('#board-bench'),
  );
  useEffect(() => {
    const onHash = () => setOn(window.location.hash.startsWith('#board-bench'));
    window.addEventListener('hashchange', onHash);
    window.__woboBoardBench = () => {
      window.location.hash = 'board-bench';
    };
    return () => window.removeEventListener('hashchange', onHash);
  }, []);
  if (!import.meta.env.DEV || !on) return null;
  return <BoardBench />;
}

export { GOLDEN_BOARDS, goldenBoard };
